"""One-off script to build pose_prompts.json / expression_prompts.json. Run: python _generate_catalogs.py"""
import json
import os

# Catalogs now live in services/prompts/ (one folder up, then into prompts).
base = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "prompts"
)

pose_templates = [
    "standing upright with arms relaxed at sides",
    "standing with hands on hips",
    "standing with arms crossed",
    "standing with one hand raised in a wave",
    "standing saluting",
    "standing stretched tall reaching toward the sky",
    "standing in a contrapposto relaxed stance",
    "walking forward mid-stride",
    "walking casually with hands in pockets",
    "jogging lightly",
    "running fast sprint pose",
    "running with arms pumping",
    "crouching low ready to jump",
    "squatting deep with knees bent",
    "squatting on toes balancing",
    "kneeling on one knee",
    "kneeling upright with torso straight",
    "sitting on the ground legs crossed",
    "sitting on a chair upright",
    "sitting slouched relaxed",
    "lying on back looking up",
    "lying on side propped on elbow",
    "lying face down on stomach",
    "push-up position plank",
    "mid-air jump legs tucked",
    "mid-air jump legs extended",
    "jumping jack pose arms and legs spread",
    "lunging forward one leg bent",
    "side lunge stretching",
    "wide stance power pose",
    "stretching arms overhead to one side",
    "touching toes forward fold",
    "yoga tree pose one foot on inner thigh",
    "yoga warrior two stance",
    "yoga downward dog",
    "ballet first position",
    "dancing spin with arms out",
    "dancing arms raised above head",
    "fighting stance fists raised",
    "punching straight forward",
    "defensive guard arms blocking",
    "kicking high with one leg",
    "holding imaginary heavy box",
    "carrying bag over shoulder",
    "lifting barbell overhead",
    "crawling on hands and knees",
    "tiptoeing quietly",
    "leaning against wall casual",
    "leaning forward hands on knees catching breath",
    "hands clasped behind back standing",
    "pointing index finger forward",
    "shrugging with palms up",
    "facepalming one hand on forehead",
    "thinking pose hand on chin",
    "arms wide open welcoming",
    "bowing slightly forward respectfully",
    "polite bow with hands together",
    "sitting on heels seiza style",
    "perched on edge of seat leaning in",
    "reclining legs extended lazy",
    "side plank balance on one arm",
    "cartwheel freeze frame",
    "cartwheel landing pose",
    "spinning on one foot ballet",
    "ice skating glide pose",
    "skiing tuck position",
    "surfboard balance stance",
    "swimming crawl stroke mid-pull",
    "climbing ladder pose one foot up",
    "reaching high on tiptoes grabbing something",
    "stooping to pick object from ground",
    "hugging self tightly",
    "holding umbrella overhead",
    "holding camera taking photo",
    "reading book held in both hands",
    "typing on invisible keyboard mid-air",
    "talking on phone held to ear",
    "shouting cupping hands around mouth",
    "whispering leaning toward viewer",
    "laughing holding belly bent slightly",
    "crying wiping eye with back of hand",
    "sleeping standing exaggerated slump",
    "marching with high knees",
    "parade rest military stance",
    "presenting with open palm toward viewer",
    "dj mixing hands on decks",
    "conducting orchestra grand gesture",
    "playing violin pose",
    "playing guitar stance",
    "playing drums mid-strike",
    "goalkeeper diving save",
    "basketball jump shot release",
    "tennis serve wind-up",
    "golf follow-through swing",
    "baseball pitching windup",
    "soccer kick planted foot",
    "rock climbing reaching for hold",
    "meditation lotus seated",
    "tai chi slow extended arms",
    "flexing biceps classic pose",
    "double biceps bodybuilding pose",
    "stretching neck side to side hands free",
    "looking over shoulder twisted torso",
    "twisting spine arms counter-rotating",
    "moonwalk slide illusion stance",
    "robot dance stiff joints",
    "breakdance freeze on one hand",
]

expr_templates = [
    "neutral calm expression",
    "soft pleasant smile",
    "wide genuine grin showing teeth",
    "subtle smirk",
    "closed-mouth polite smile",
    "bashful shy smile looking away",
    "flirtatious playful smile",
    "mischievous grin",
    "nervous tight-lipped smile",
    "bitter forced smile",
    "slight frown of concern",
    "deep furrowed-brow frown",
    "angry scowl lips pressed",
    "rage snarl showing teeth",
    "pouting lips pushed forward",
    "sulking downturned mouth",
    "disappointed sad eyes",
    "on the verge of tears glistening eyes",
    "openly crying tears streaming",
    "wailing mouth wide sorrow",
    "red puffy eyes after crying",
    "surprised eyes wide mouth open",
    "shocked jaw dropped",
    "astonished raised eyebrows",
    "mildly curious raised brow",
    "skeptical side-eye",
    "unimpressed deadpan stare",
    "bored half-lidded eyes",
    "sleepy drowsy heavy eyelids",
    "yawning exhausted",
    "focused intense gaze",
    "determined set jaw",
    "confident slight smile steely eyes",
    "glaring intense anger eyes",
    "side glance suspicious",
    "rolling eyes upward annoyance",
    "eyes closed peaceful calm",
    "eyes closed scrunched laughing hard",
    "squinting against bright light",
    "narrow suspicious eyes",
    "wide innocent doe eyes",
    "furrowed confusion",
    "puzzled head tilt expression",
    "concentrating tongue slightly out",
    "embarrassed blush cheeks looking down",
    "ashamed unable to meet eyes",
    "proud chin lifted confident",
    "arrogant smug half-smile",
    "contemptuous sneer",
    "disgusted wrinkled nose",
    "tasting something sour expression",
    "sniffing disdainful",
    "playful wink one eye",
    "both eyes squeezed shut joyful laugh",
    "mocking exaggerated smile",
    "terrified pale wide eyes",
    "anxious biting lip",
    "panicked eyes darting",
    "relieved long exhale soft eyes",
    "content serene smile eyes soft",
    "dreamy faraway gaze",
    "starstruck awe sparkling eyes",
    "envious sideways glare",
    "hurt vulnerable wounded eyes",
    "betrayed wounded disbelief",
    "cold emotionless mask-like face",
    "manic excited grin too wide",
    "delirious half-smile unfocused eyes",
    "smug eye-roll mid-expression",
    "stifling laughter pressed lips",
    "bursting laughter eyes squeezed shut",
    "silent chuckle shaking shoulders",
    "confused tilt smirk combo",
    "polite listening slight nod expression",
    "interrupting mouth opening to speak",
    "shushing finger on lips secretive",
    "blowing a kiss exaggerated",
    "duck face playful selfie",
    "fish gape meme face",
    "stink eye with nose scrunch",
    "double chin exaggerated joke face",
    "cheek puff holding breath",
    "one eyebrow raised challenge",
    "both eyebrows raised exaggerated surprise",
    "lip bite nervous flirty",
    "nose crinkle joyful smile",
    "eyes shimmering hope",
    "grim determination teeth visible slight snarl",
    "broken smile sad eyes smiling lips",
    "thousand-yard stare hollow eyes",
    "zen patient faint smile",
    "maternal gentle warm eyes",
    "stern disapproval look",
    "childlike wonder bright eyes",
    "older wise knowing half-smile",
    "villainous grin narrowed eyes",
    "heroic inspiring steadfast gaze",
    "shy peek from behind hands",
    "peekaboo hands covering eyes playful",
    "ducking scared hands over head",
    "sucking on straw casual mood",
    "chewing thoughtful food mid-bite face",
    "pinching bridge of nose headache stress",
    "massaging temples stressed",
]

while len(pose_templates) < 100:
    pose_templates.append(
        "dynamic action pose variation %d" % len(pose_templates)
    )
while len(expr_templates) < 100:
    expr_templates.append(
        "facial expression variation %d" % len(expr_templates)
    )
pose_templates = pose_templates[:100]
expr_templates = expr_templates[:100]

poses = [
    {
        "id": i,
        "label": p[:60],
        "prompt_text": "Edit the subject to "
        + p
        + ", keep identity and clothing coherent unless impossible.",
    }
    for i, p in enumerate(pose_templates)
]
exprs = [
    {
        "id": i,
        "label": e[:60],
        "prompt_text": "Edit the face to show "
        + e
        + ", keep identity coherent.",
    }
    for i, e in enumerate(expr_templates)
]

with open(os.path.join(base, "pose_prompts.json"), "w", encoding="utf-8") as f:
    json.dump(poses, f, indent=2, ensure_ascii=False)
with open(os.path.join(base, "expression_prompts.json"), "w", encoding="utf-8") as f:
    json.dump(exprs, f, indent=2, ensure_ascii=False)
print("wrote pose_prompts.json and expression_prompts.json (100 each)")
